spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551409
    password: 280702
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update